app = "n8n-agent-supra"
primary_region = "gru"

[build]
image = "n8nio/n8n"

[[services]]
protocol = "tcp"
internal_port = 5678

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[deploy]
release_command = "n8n start"