app = "n8n-agent-supra"
primary_region = "gru"

[build]
  image = "docker.io/n8nio/n8n:1.39.1"

[[services]]
  internal_port = 5678
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
